name: Playwright Test
on:
    schedule:
        - cron: "30 16 * * *"
jobs:
    run-playwright-tests:
        name: Run Playwright Tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10.11'
            
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Install Playwright Browsers
              run: playwright install
            
            - name: Run Playwright Test
              run: pytest --headless

            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              if: ${{!cancelled()}}
              with:
                name: playwright-traces
                path: test-results/
